### ISSUE TITLE
Tetra Compatability w/ Mob Effects

### ISSUE THREAD

**Issue by anIceyGirl** [OreCruncher/DynamicSurroundings2#4] opened 2021-01-24 12:47 UTC
Exactly what the title suggests: Native compatibility with the latest version of [Tetra](https://github.com/mickelus/tetra). [(Curseforge Link)](https://www.curseforge.com/minecraft/mc-mods/tetra) 

It's a little bit jarring for me to equip my sword and not play the unsheathing sound, and the same goes for pickaxes, shovels, axes... you get the picture.

**Comment by OreCruncher** [comment] 2021-01-24 14:06
Dupe of **https://github.com/OreCruncher/DynamicSurroundings/issues/628**

**Closed as completed by OreCruncher** 2021-01-24 14:06 UTC
